import { Match, Prediction, ChatMessage, Notification } from '@/services/types';

export const MOCK_MATCHES: Match[] = [
  // ---- LIVE FOOTBALL ----
  {
    id: 'match-1',
    sport: 'Football',
    homeTeam: 'Manchester City',
    awayTeam: 'Real Madrid',
    homeScore: 2,
    awayScore: 1,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'UEFA Champions League',
    venue: 'Etihad Stadium',
    minute: 67,
    homeOdds: 1.85,
    drawOdds: 3.50,
    awayOdds: 4.20,
  },
  {
    id: 'match-2',
    sport: 'Football',
    homeTeam: 'Arsenal',
    awayTeam: 'Bayern Munich',
    homeScore: 1,
    awayScore: 1,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'UEFA Champions League',
    venue: 'Emirates Stadium',
    minute: 43,
    homeOdds: 2.40,
    drawOdds: 3.20,
    awayOdds: 2.90,
  },
  // ---- UPCOMING FOOTBALL ----
  {
    id: 'match-3',
    sport: 'Football',
    homeTeam: 'Liverpool',
    awayTeam: 'Chelsea',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 2).toISOString(),
    league: 'Premier League',
    venue: 'Anfield',
    minute: 0,
    homeOdds: 1.70,
    drawOdds: 3.80,
    awayOdds: 5.00,
  },
  {
    id: 'match-4',
    sport: 'Football',
    homeTeam: 'Barcelona',
    awayTeam: 'Atletico Madrid',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 5).toISOString(),
    league: 'La Liga',
    venue: 'Camp Nou',
    minute: 0,
    homeOdds: 1.90,
    drawOdds: 3.40,
    awayOdds: 4.00,
  },
  {
    id: 'match-5',
    sport: 'Football',
    homeTeam: 'PSG',
    awayTeam: 'Inter Milan',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 8).toISOString(),
    league: 'UEFA Champions League',
    venue: 'Parc des Princes',
    minute: 0,
    homeOdds: 2.10,
    drawOdds: 3.30,
    awayOdds: 3.60,
  },
  // ---- FINISHED FOOTBALL ----
  {
    id: 'match-6',
    sport: 'Football',
    homeTeam: 'Man United',
    awayTeam: 'Tottenham',
    homeScore: 3,
    awayScore: 1,
    status: 'finished',
    matchTime: new Date(Date.now() - 3600000 * 3).toISOString(),
    league: 'Premier League',
    venue: 'Old Trafford',
    minute: 90,
    homeOdds: 2.20,
    drawOdds: 3.50,
    awayOdds: 3.10,
  },
  // ---- LIVE BASKETBALL ----
  {
    id: 'match-7',
    sport: 'Basketball',
    homeTeam: 'LA Lakers',
    awayTeam: 'Golden State',
    homeScore: 87,
    awayScore: 92,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'NBA',
    venue: 'Crypto.com Arena',
    minute: 34,
    homeOdds: 1.95,
    drawOdds: 0,
    awayOdds: 1.90,
    stats: { home_q1: 22, home_q2: 31, home_q3: 18, home_q4: null, away_q1: 28, away_q2: 27, away_q3: 24, away_q4: null },
  },
  // ---- UPCOMING BASKETBALL ----
  {
    id: 'match-8',
    sport: 'Basketball',
    homeTeam: 'Boston Celtics',
    awayTeam: 'Miami Heat',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 4).toISOString(),
    league: 'NBA',
    venue: 'TD Garden',
    minute: 0,
    homeOdds: 1.65,
    drawOdds: 0,
    awayOdds: 2.30,
    stats: null,
  },
  {
    id: 'match-11',
    sport: 'Basketball',
    homeTeam: 'Real Madrid',
    awayTeam: 'CSKA Moscow',
    homeScore: 68,
    awayScore: 61,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'EuroLeague',
    venue: 'WiZink Center',
    minute: 0,
    homeOdds: 1.55,
    drawOdds: 0,
    awayOdds: 2.60,
    stats: { home_q1: 18, home_q2: 22, home_q3: 14, home_q4: null, away_q1: 16, away_q2: 19, away_q3: 14, away_q4: null },
  },
  {
    id: 'match-12',
    sport: 'Basketball',
    homeTeam: 'Fenerbahce',
    awayTeam: 'Olympiacos',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 7).toISOString(),
    league: 'EuroLeague',
    venue: 'Ulker Sports Arena',
    minute: 0,
    homeOdds: 1.72,
    drawOdds: 0,
    awayOdds: 2.15,
    stats: null,
  },
  // ---- UPCOMING TENNIS ----
  {
    id: 'match-9',
    sport: 'Tennis',
    homeTeam: 'C. Alcaraz',
    awayTeam: 'N. Djokovic',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 6).toISOString(),
    league: 'Roland Garros',
    venue: 'Court Philippe-Chatrier',
    minute: 0,
    homeOdds: 1.80,
    drawOdds: 0,
    awayOdds: 2.00,
    stats: { home_sets: 0, away_sets: 0 },
  },
  {
    id: 'match-10',
    sport: 'Tennis',
    homeTeam: 'J. Sinner',
    awayTeam: 'A. Zverev',
    homeScore: 1,
    awayScore: 2,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'Roland Garros',
    venue: 'Court Suzanne-Lenglen',
    minute: 0,
    homeOdds: 1.75,
    drawOdds: 0,
    awayOdds: 2.10,
    stats: { home_sets: 1, away_sets: 2 },
  },
  {
    id: 'match-13',
    sport: 'Tennis',
    homeTeam: 'C. Gauff',
    awayTeam: 'I. Swiatek',
    homeScore: 2,
    awayScore: 1,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'Wimbledon',
    venue: 'Centre Court',
    minute: 0,
    homeOdds: 2.20,
    drawOdds: 0,
    awayOdds: 1.70,
    stats: { home_sets: 2, away_sets: 1 },
  },

  // ---- BASEBALL ----
  {
    id: 'match-14',
    sport: 'baseball',
    homeTeam: 'New York Yankees',
    awayTeam: 'Los Angeles Dodgers',
    homeScore: 4,
    awayScore: 2,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'MLB',
    venue: 'Yankee Stadium',
    minute: 0,
    homeOdds: 1.88,
    drawOdds: 0,
    awayOdds: 1.98,
    stats: { home_hits: 7, away_hits: 5, home_errors: 0, away_errors: 1 },
  },
  {
    id: 'match-15',
    sport: 'baseball',
    homeTeam: 'Houston Astros',
    awayTeam: 'Boston Red Sox',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 3).toISOString(),
    league: 'MLB',
    venue: 'Minute Maid Park',
    minute: 0,
    homeOdds: 1.75,
    drawOdds: 0,
    awayOdds: 2.15,
    stats: null,
  },
  {
    id: 'match-16',
    sport: 'baseball',
    homeTeam: 'Chicago Cubs',
    awayTeam: 'San Francisco Giants',
    homeScore: 6,
    awayScore: 3,
    status: 'finished',
    matchTime: new Date(Date.now() - 3600000 * 4).toISOString(),
    league: 'MLB',
    venue: 'Wrigley Field',
    minute: 0,
    homeOdds: 1.92,
    drawOdds: 0,
    awayOdds: 1.95,
    stats: { home_hits: 10, away_hits: 8, home_errors: 1, away_errors: 2 },
  },

  // ---- HOCKEY ----
  {
    id: 'match-17',
    sport: 'hockey',
    homeTeam: 'Toronto Maple Leafs',
    awayTeam: 'Montreal Canadiens',
    homeScore: 3,
    awayScore: 2,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'NHL',
    venue: 'Scotiabank Arena',
    minute: 0,
    homeOdds: 1.80,
    drawOdds: 0,
    awayOdds: 2.10,
    stats: { period_1_home: 1, period_2_home: 2, period_3_home: null, overtime: null },
  },
  {
    id: 'match-18',
    sport: 'hockey',
    homeTeam: 'Boston Bruins',
    awayTeam: 'Tampa Bay Lightning',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 5).toISOString(),
    league: 'NHL',
    venue: 'TD Garden',
    minute: 0,
    homeOdds: 1.95,
    drawOdds: 0,
    awayOdds: 1.90,
    stats: null,
  },
  {
    id: 'match-19',
    sport: 'hockey',
    homeTeam: 'Pittsburgh Penguins',
    awayTeam: 'Washington Capitals',
    homeScore: 4,
    awayScore: 1,
    status: 'finished',
    matchTime: new Date(Date.now() - 3600000 * 5).toISOString(),
    league: 'NHL',
    venue: 'PPG Paints Arena',
    minute: 0,
    homeOdds: 1.78,
    drawOdds: 0,
    awayOdds: 2.20,
    stats: { period_1_home: 2, period_2_home: 1, period_3_home: 1, overtime: null },
  },

  // ---- RUGBY ----
  {
    id: 'match-20',
    sport: 'rugby',
    homeTeam: 'New Zealand',
    awayTeam: 'South Africa',
    homeScore: 17,
    awayScore: 14,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'Rugby World Cup',
    venue: 'Eden Park, Auckland',
    minute: 0,
    homeOdds: 1.65,
    drawOdds: 0,
    awayOdds: 2.30,
    stats: null,
  },
  {
    id: 'match-21',
    sport: 'rugby',
    homeTeam: 'England',
    awayTeam: 'Australia',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 6).toISOString(),
    league: 'Rugby World Cup',
    venue: 'Twickenham Stadium',
    minute: 0,
    homeOdds: 1.72,
    drawOdds: 0,
    awayOdds: 2.20,
    stats: null,
  },
  {
    id: 'match-22',
    sport: 'rugby',
    homeTeam: 'Ireland',
    awayTeam: 'France',
    homeScore: 28,
    awayScore: 22,
    status: 'finished',
    matchTime: new Date(Date.now() - 3600000 * 6).toISOString(),
    league: 'Six Nations',
    venue: 'Aviva Stadium, Dublin',
    minute: 0,
    homeOdds: 1.85,
    drawOdds: 0,
    awayOdds: 2.00,
    stats: null,
  },

  // ---- HANDBALL ----
  {
    id: 'match-23',
    sport: 'handball',
    homeTeam: 'PSG Handball',
    awayTeam: 'FC Barcelona Handbol',
    homeScore: 18,
    awayScore: 16,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'EHF Champions League',
    venue: 'Palais des Sports, Paris',
    minute: 0,
    homeOdds: 2.00,
    drawOdds: 0,
    awayOdds: 1.85,
    stats: null,
  },
  {
    id: 'match-24',
    sport: 'handball',
    homeTeam: 'THW Kiel',
    awayTeam: 'SG Flensburg-Handewitt',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 4).toISOString(),
    league: 'Handball Bundesliga',
    venue: 'Sparkassen Arena-Kiel',
    minute: 0,
    homeOdds: 1.70,
    drawOdds: 0,
    awayOdds: 2.25,
    stats: null,
  },
  {
    id: 'match-25',
    sport: 'handball',
    homeTeam: 'Vive Kielce',
    awayTeam: 'Lomza Industria Kielce',
    homeScore: 32,
    awayScore: 28,
    status: 'finished',
    matchTime: new Date(Date.now() - 3600000 * 7).toISOString(),
    league: 'EHF Champions League',
    venue: 'Hala Legionow, Kielce',
    minute: 0,
    homeOdds: 1.55,
    drawOdds: 0,
    awayOdds: 2.60,
    stats: null,
  },

  // ---- VOLLEYBALL ----
  {
    id: 'match-26',
    sport: 'volleyball',
    homeTeam: 'Brazil',
    awayTeam: 'Poland',
    homeScore: 2,
    awayScore: 1,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'Volleyball Nations League',
    venue: 'Nilson Nelson Gymnasium, Brasilia',
    minute: 0,
    homeOdds: 1.75,
    drawOdds: 0,
    awayOdds: 2.10,
    stats: { home_s1: 25, home_s2: 22, home_s3: null, away_s1: 22, away_s2: 25, away_s3: null },
  },
  {
    id: 'match-27',
    sport: 'volleyball',
    homeTeam: 'Italy',
    awayTeam: 'USA',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 5).toISOString(),
    league: 'Volleyball Nations League',
    venue: 'Pala EUR, Rome',
    minute: 0,
    homeOdds: 1.90,
    drawOdds: 0,
    awayOdds: 1.95,
    stats: null,
  },
  {
    id: 'match-28',
    sport: 'volleyball',
    homeTeam: 'France',
    awayTeam: 'Serbia',
    homeScore: 3,
    awayScore: 1,
    status: 'finished',
    matchTime: new Date(Date.now() - 3600000 * 8).toISOString(),
    league: 'CEV Champions League',
    venue: 'Palais des Sports, Poitiers',
    minute: 0,
    homeOdds: 1.68,
    drawOdds: 0,
    awayOdds: 2.28,
    stats: { home_s1: 25, home_s2: 19, home_s3: 25, away_s1: 22, away_s2: 25, away_s3: 20 },
  },

  // ---- AMERICAN FOOTBALL ----
  {
    id: 'match-29',
    sport: 'american-football',
    homeTeam: 'Kansas City Chiefs',
    awayTeam: 'San Francisco 49ers',
    homeScore: 17,
    awayScore: 14,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'NFL',
    venue: 'Arrowhead Stadium',
    minute: 0,
    homeOdds: 1.82,
    drawOdds: 0,
    awayOdds: 2.05,
    stats: { home_q1: 7, home_q2: 10, home_q3: 0, home_q4: null, away_q1: 0, away_q2: 7, away_q3: 7, away_q4: null },
  },
  {
    id: 'match-30',
    sport: 'american-football',
    homeTeam: 'Dallas Cowboys',
    awayTeam: 'Philadelphia Eagles',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 7).toISOString(),
    league: 'NFL',
    venue: 'AT&T Stadium',
    minute: 0,
    homeOdds: 2.10,
    drawOdds: 0,
    awayOdds: 1.78,
    stats: null,
  },
  {
    id: 'match-31',
    sport: 'american-football',
    homeTeam: 'Buffalo Bills',
    awayTeam: 'Miami Dolphins',
    homeScore: 35,
    awayScore: 17,
    status: 'finished',
    matchTime: new Date(Date.now() - 3600000 * 9).toISOString(),
    league: 'NFL',
    venue: 'Highmark Stadium',
    minute: 0,
    homeOdds: 1.65,
    drawOdds: 0,
    awayOdds: 2.35,
    stats: { home_q1: 7, home_q2: 14, home_q3: 7, home_q4: 7, away_q1: 0, away_q2: 10, away_q3: 7, away_q4: 0 },
  },

  // ---- CRICKET ----
  {
    id: 'match-32',
    sport: 'cricket',
    homeTeam: 'India',
    awayTeam: 'Australia',
    homeScore: 287,
    awayScore: 241,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'ICC Test Championship',
    venue: 'Wankhede Stadium, Mumbai',
    minute: 0,
    homeOdds: 1.70,
    drawOdds: 3.00,
    awayOdds: 2.40,
    stats: null,
  },
  {
    id: 'match-33',
    sport: 'cricket',
    homeTeam: 'England',
    awayTeam: 'Pakistan',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 10).toISOString(),
    league: 'ICC T20 World Cup',
    venue: "Lord's Cricket Ground, London",
    minute: 0,
    homeOdds: 1.85,
    drawOdds: 0,
    awayOdds: 2.00,
    stats: null,
  },
  {
    id: 'match-34',
    sport: 'cricket',
    homeTeam: 'South Africa',
    awayTeam: 'New Zealand',
    homeScore: 312,
    awayScore: 289,
    status: 'finished',
    matchTime: new Date(Date.now() - 3600000 * 12).toISOString(),
    league: 'ICC ODI World Cup',
    venue: 'Newlands, Cape Town',
    minute: 0,
    homeOdds: 1.80,
    drawOdds: 2.80,
    awayOdds: 2.10,
    stats: null,
  },

  // ---- MMA ----
  {
    id: 'match-35',
    sport: 'mma',
    homeTeam: 'Jon Jones',
    awayTeam: 'Stipe Miocic',
    homeScore: 0,
    awayScore: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000 * 12).toISOString(),
    league: 'UFC 309',
    venue: 'Madison Square Garden, New York',
    minute: 0,
    homeOdds: 1.40,
    drawOdds: 0,
    awayOdds: 3.00,
    stats: null,
  },
  {
    id: 'match-36',
    sport: 'mma',
    homeTeam: 'Islam Makhachev',
    awayTeam: 'Charles Oliveira',
    homeScore: 1,
    awayScore: 0,
    status: 'live',
    matchTime: new Date().toISOString(),
    league: 'UFC 302',
    venue: 'Prudential Center, Newark',
    minute: 0,
    homeOdds: 1.50,
    drawOdds: 0,
    awayOdds: 2.75,
    stats: null,
  },
  {
    id: 'match-37',
    sport: 'mma',
    homeTeam: 'Alex Pereira',
    awayTeam: 'Jiri Prochazka',
    homeScore: 1,
    awayScore: 0,
    status: 'finished',
    matchTime: new Date(Date.now() - 3600000 * 10).toISOString(),
    league: 'UFC 303',
    venue: 'T-Mobile Arena, Las Vegas',
    minute: 0,
    homeOdds: 1.60,
    drawOdds: 0,
    awayOdds: 2.50,
    stats: null,
  },
];

export const MOCK_PREDICTIONS: Prediction[] = [
  {
    id: 'pred-1',
    matchId: 'match-1',
    homeWinProb: 52,
    drawProb: 21,
    awayWinProb: 27,
    predictedResult: 'home_win',
    confidence: 84,
    overUnder: 'over',
    overUnderLine: 2.5,
    btts: 'yes',
    aiAnalysis: 'Manchester City show dominant form at home with 78% possession average. Real Madrid defensively vulnerable in away legs this season. Haaland fitness confirmed — expect clinical finishing.',
    keyFactors: ['City 6W-1D-1L home form', 'Haaland back from injury', 'Madrid 3 away losses UCL', 'xG City 2.4 vs Madrid 1.1'],
    vipTip: 'Both teams to score + Over 2.5 @ 1.72',
  },
  {
    id: 'pred-2',
    matchId: 'match-3',
    homeWinProb: 48,
    drawProb: 28,
    awayWinProb: 24,
    predictedResult: 'home_win',
    confidence: 71,
    overUnder: 'over',
    overUnderLine: 2.5,
    btts: 'yes',
    aiAnalysis: 'Liverpool vs Chelsea historically produces goals. Slot system generating 2.1 xG average at Anfield. Chelsea attackers in fine individual form but away defensive record shows vulnerabilities.',
    keyFactors: ['Liverpool 5 consecutive home wins', 'Chelsea 4 goals in last 2 away', 'Anfield atmosphere factor', 'H2H: 4/5 Over 2.5'],
    vipTip: 'Liverpool Win + BTTS @ 2.40',
  },
  {
    id: 'pred-3',
    matchId: 'match-4',
    homeWinProb: 61,
    drawProb: 22,
    awayWinProb: 17,
    predictedResult: 'home_win',
    confidence: 88,
    overUnder: 'under',
    overUnderLine: 2.5,
    btts: 'no',
    aiAnalysis: 'Barcelona at Camp Nou are near unbeatable this season. Atletico Madrid rely on defensive solidity — expect a tight first half. Late Barca winner most likely based on second-half surge patterns.',
    keyFactors: ['Barca unbeaten 9 home La Liga', 'Atletico 5 clean sheets away', 'Yamal 6 assists last 5', 'Simeone defensive setup vs top clubs'],
    vipTip: 'Barcelona to Win + Under 2.5 @ 2.10',
  },
  {
    id: 'pred-4',
    matchId: 'match-7',
    homeWinProb: 44,
    drawProb: 0,
    awayWinProb: 56,
    predictedResult: 'away_win',
    confidence: 67,
    overUnder: 'over',
    overUnderLine: 215.5,
    btts: 'yes',
    aiAnalysis: 'Golden State Warriors outperforming on points per possession this season. LeBron showing wear in back-to-back games. Warriors three-point volume will be decisive — Curry off to historic pace.',
    keyFactors: ['Warriors +7.3 net rating last 10', 'LeBron back-to-back fatigue', 'Curry 45.2% from three', 'Lakers 3-7 vs top-8 Western Conference'],
    vipTip: 'Warriors -4.5 Spread @ 1.91',
  },
  {
    id: 'pred-5',
    matchId: 'match-9',
    homeWinProb: 55,
    drawProb: 0,
    awayWinProb: 45,
    predictedResult: 'home_win',
    confidence: 73,
    overUnder: 'over',
    overUnderLine: 35.5,
    btts: 'yes',
    aiAnalysis: 'Alcaraz on clay is exceptional — Roland Garros specialist with heavy topspin that troubles Djokovic. However Djokovic Grand Slam experience and mental fortitude make this a potential 5-set thriller.',
    keyFactors: ['Alcaraz 12-2 on clay 2025', 'Djokovic 87% GS win rate', 'H2H Clay: Alcaraz 3-2', 'Expected 4-5 sets high-intensity'],
    vipTip: 'Alcaraz to Win in 4+ Sets @ 2.85',
  },

  // ---- BASEBALL PREDICTIONS ----
  {
    id: 'pred-6',
    matchId: 'match-14',
    homeWinProb: 58,
    drawProb: 0,
    awayWinProb: 42,
    predictedResult: 'home_win',
    confidence: 76,
    overUnder: 'over',
    overUnderLine: 8.5,
    btts: 'yes',
    aiAnalysis: 'Yankees at home have a strong pitching matchup advantage. Their rotation ERA of 3.21 at Yankee Stadium this season is elite. Dodgers offense has underperformed on the road in recent series.',
    keyFactors: ['Yankees 8-2 home record vs NL opponents', 'Dodgers 4-6 road last 10', 'Starting pitcher ERA: NYY 3.21 vs LAD 4.08', 'Yankees lead MLB in home run differential'],
    vipTip: 'Yankees ML + Over 8.5 Runs @ 2.30',
  },
  {
    id: 'pred-7',
    matchId: 'match-15',
    homeWinProb: 62,
    drawProb: 0,
    awayWinProb: 38,
    predictedResult: 'home_win',
    confidence: 81,
    overUnder: 'under',
    overUnderLine: 8.5,
    btts: 'yes',
    aiAnalysis: 'Astros rotation is dominant at Minute Maid Park. Verlander-led pitching has held opponents to under 3 runs in 6 of the last 8 home games. Red Sox batting average drops 47 points on the road.',
    keyFactors: ['Astros SP ERA 2.89 last 15 home starts', 'Red Sox .231 road batting avg', 'Minute Maid Park pitcher-friendly dimensions', 'H2H: Astros 7-3 last 10 meetings'],
    vipTip: 'Astros -1.5 Run Line @ 2.05',
  },

  // ---- HOCKEY PREDICTIONS ----
  {
    id: 'pred-8',
    matchId: 'match-17',
    homeWinProb: 55,
    drawProb: 0,
    awayWinProb: 45,
    predictedResult: 'home_win',
    confidence: 69,
    overUnder: 'over',
    overUnderLine: 5.5,
    btts: 'yes',
    aiAnalysis: 'Maple Leafs vs Canadiens is always a high-stakes rivalry. Toronto leads in power play efficiency this season. Montreal has allowed 3+ goals in 4 of their last 5 away games.',
    keyFactors: ['Leafs 22.1% power play conversion', 'Canadiens 3.4 GAA on road', 'Matthews averaging 1.2 points/game', 'H2H: Over 5.5 in 5 of last 6 meetings'],
    vipTip: 'Both Teams to Score + Over 5.5 @ 1.88',
  },
  {
    id: 'pred-9',
    matchId: 'match-18',
    homeWinProb: 52,
    drawProb: 0,
    awayWinProb: 48,
    predictedResult: 'home_win',
    confidence: 64,
    overUnder: 'under',
    overUnderLine: 5.5,
    btts: 'yes',
    aiAnalysis: 'Bruins vs Lightning is historically a tight playoff-intensity matchup. Both teams have elite goaltending this season — Ullmark and Vasilevskiy are top-5 in save percentage. Expect a low-scoring battle.',
    keyFactors: ['Ullmark .921 SV% at home', 'Vasilevskiy .924 SV% road', 'Last 5 H2H: avg 4.8 goals', 'Both teams top-3 NHL penalty kill'],
    vipTip: 'Under 5.5 Goals @ 1.90',
  },

  // ---- RUGBY PREDICTIONS ----
  {
    id: 'pred-10',
    matchId: 'match-20',
    homeWinProb: 64,
    drawProb: 2,
    awayWinProb: 34,
    predictedResult: 'home_win',
    confidence: 78,
    overUnder: 'over',
    overUnderLine: 42.5,
    btts: 'yes',
    aiAnalysis: 'All Blacks at Eden Park are historically unbeatable — 49 consecutive home wins at this venue. Springboks are the world champions but have lost 3 of last 4 visits to Auckland.',
    keyFactors: ['NZ unbeaten Eden Park 49 games', 'SA 1-3 last 4 Auckland visits', 'All Blacks avg 32 points at home', 'Line-out and scrum dominance at altitude'],
    vipTip: 'New Zealand -7.5 Handicap @ 1.95',
  },
  {
    id: 'pred-11',
    matchId: 'match-21',
    homeWinProb: 57,
    drawProb: 1,
    awayWinProb: 42,
    predictedResult: 'home_win',
    confidence: 72,
    overUnder: 'over',
    overUnderLine: 44.5,
    btts: 'yes',
    aiAnalysis: 'England at Twickenham are formidable with massive crowd support. Australia has been inconsistent in Northern Hemisphere tours. England scrum dominance should translate to territory and set-piece advantage.',
    keyFactors: ['England 7-1 Twickenham last 2 seasons', 'Australia 4-6 NH tours last 5 years', 'England avg 31 pts home vs Tier 1', 'Wallabies lose turnover battle on tour'],
    vipTip: 'England to Win + Over 44.5 Points @ 2.10',
  },

  // ---- HANDBALL PREDICTIONS ----
  {
    id: 'pred-12',
    matchId: 'match-23',
    homeWinProb: 48,
    drawProb: 0,
    awayWinProb: 52,
    predictedResult: 'away_win',
    confidence: 67,
    overUnder: 'over',
    overUnderLine: 57.5,
    btts: 'yes',
    aiAnalysis: 'Barcelona Handbol are the most decorated club in EHF history and consistently excel in French arenas. PSG have home advantage but Barcelona attack pace and pivot play should prove decisive in the second half.',
    keyFactors: ['Barcelona 6 EHF Champions League titles', 'Cindric averaging 8.2 goals/game', 'PSG concede 28+ in 4 of last 5 home EHF', 'Both teams avg 30+ goals per match'],
    vipTip: 'Barcelona Handbol Win + Over 57.5 @ 2.45',
  },
  {
    id: 'pred-13',
    matchId: 'match-24',
    homeWinProb: 61,
    drawProb: 0,
    awayWinProb: 39,
    predictedResult: 'home_win',
    confidence: 74,
    overUnder: 'over',
    overUnderLine: 60.5,
    btts: 'yes',
    aiAnalysis: 'THW Kiel at home in the Bundesliga is a formidable proposition. The Zebras have a historic rivalry with Flensburg and tend to elevate performance in this fixture. Kiel attack runs at 35+ goals at home.',
    keyFactors: ['Kiel 8-2 home Bundesliga record', 'Sagosen leads Bundesliga scoring', 'Flensburg 3-5 away form last 8', 'H2H Kiel home: 6-1 last 7'],
    vipTip: 'Kiel -3.5 Handicap @ 1.88',
  },

  // ---- VOLLEYBALL PREDICTIONS ----
  {
    id: 'pred-14',
    matchId: 'match-26',
    homeWinProb: 60,
    drawProb: 0,
    awayWinProb: 40,
    predictedResult: 'home_win',
    confidence: 77,
    overUnder: 'over',
    overUnderLine: 3.5,
    btts: 'yes',
    aiAnalysis: 'Brazil on home soil in the VNL is electric. Polish side are strong but struggle with Brazilian serving intensity and quick attack patterns from Leal and Lucao.',
    keyFactors: ['Brazil 9-1 home VNL record', 'Leal averaging 18 points/set', 'Poland 3 road defeats last 5', 'H2H: Brazil 7-3 last 10 VNL meetings'],
    vipTip: 'Brazil 3-1 Correct Score @ 3.20',
  },
  {
    id: 'pred-15',
    matchId: 'match-27',
    homeWinProb: 52,
    drawProb: 0,
    awayWinProb: 48,
    predictedResult: 'home_win',
    confidence: 65,
    overUnder: 'over',
    overUnderLine: 3.5,
    btts: 'yes',
    aiAnalysis: 'Italy vs USA in volleyball is always a contested five-setter battle. Italy have home advantage and are playing a more structured serve-receive system this season. USA rely on individual brilliance from Christenson.',
    keyFactors: ['Italy 6-1 Rome home record 2025', 'USA road conversion rate 58%', 'Giannelli setting consistency 9.1 exc/set', 'H2H: 5-5 last 10 VNL meetings'],
    vipTip: 'Italy Win in 5 Sets @ 4.10',
  },

  // ---- AMERICAN FOOTBALL PREDICTIONS ----
  {
    id: 'pred-16',
    matchId: 'match-29',
    homeWinProb: 58,
    drawProb: 0,
    awayWinProb: 42,
    predictedResult: 'home_win',
    confidence: 79,
    overUnder: 'over',
    overUnderLine: 47.5,
    btts: 'yes',
    aiAnalysis: 'Chiefs at Arrowhead are the gold standard of NFL home dominance. Mahomes vs Purdy is the defining QB rivalry of this era. KC defense has held opponents to under 17 points in 5 of last 7 home games.',
    keyFactors: ['Chiefs 14-2 home record last 2 seasons', 'Mahomes 112.3 home passer rating', '49ers 0-4 road vs elite defenses', 'Travis Kelce dominant in prime-time matchups'],
    vipTip: 'Chiefs -3.5 Spread + Over 47.5 @ 2.15',
  },
  {
    id: 'pred-17',
    matchId: 'match-30',
    homeWinProb: 43,
    drawProb: 0,
    awayWinProb: 57,
    predictedResult: 'away_win',
    confidence: 71,
    overUnder: 'over',
    overUnderLine: 48.5,
    btts: 'yes',
    aiAnalysis: 'Eagles travel to AT&T Stadium as the better-performing team this season. Hurts is playing at MVP level and Philadelphia offensive line outranks Dallas significantly. Cowboys secondary has been exploited through the air.',
    keyFactors: ['Eagles 9-3 road record this season', 'Hurts 28 TD 5 INT road games', 'Cowboys CB injuries in secondary', 'H2H: Eagles 5-1 last 6 meetings'],
    vipTip: 'Eagles -2.5 Spread @ 1.95',
  },

  // ---- CRICKET PREDICTIONS ----
  {
    id: 'pred-18',
    matchId: 'match-32',
    homeWinProb: 55,
    drawProb: 20,
    awayWinProb: 25,
    predictedResult: 'home_win',
    confidence: 74,
    overUnder: 'over',
    overUnderLine: 550.5,
    btts: 'yes',
    aiAnalysis: 'India at Wankhede are virtually unbeatable — the pitch favours spin and India have three world-class spinners. Australia struggle on subcontinent turning tracks. Kohli returning to form is the defining factor.',
    keyFactors: ['India 14-2 home Test record last 5 years', 'Australia avg 210 in 2nd innings on subcont.', 'Wankhede pitch spin-friendly day 3+', 'Bumrah 4.1 wickets avg in home Tests'],
    vipTip: 'India to Win Test Match @ 1.75',
  },
  {
    id: 'pred-19',
    matchId: 'match-33',
    homeWinProb: 52,
    drawProb: 0,
    awayWinProb: 48,
    predictedResult: 'home_win',
    confidence: 68,
    overUnder: 'over',
    overUnderLine: 320.5,
    btts: 'yes',
    aiAnalysis: "England in T20 cricket are one of the most explosive batting units in the world. Pakistan pace attack is dangerous but England Bazball approach overwhelms even elite bowling. Expect a high-scoring thriller.",
    keyFactors: ['England T20 NRR +2.31 this tournament', 'Buttler avg 48.3 in knockout T20 games', "Pakistan spinners effective at Lord's", 'H2H T20: England 4-3 last 7'],
    vipTip: 'England to Win + Over 320.5 Total Runs @ 2.55',
  },

  // ---- MMA PREDICTIONS ----
  {
    id: 'pred-20',
    matchId: 'match-35',
    homeWinProb: 72,
    drawProb: 0,
    awayWinProb: 28,
    predictedResult: 'home_win',
    confidence: 82,
    overUnder: 'under',
    overUnderLine: 2.5,
    btts: 'yes',
    aiAnalysis: 'Jon Jones remains pound-for-pound the greatest and has a clear physical and technical edge over Miocic at heavyweight. Jones grappling and IQ have not diminished — expect a finish inside 2 rounds.',
    keyFactors: ['Jones 11 UFC title defenses', 'Miocic 37 years old — power still elite', 'Jones 74% finish rate in title fights', 'Jones body shots decisive vs Miocic chin'],
    vipTip: 'Jones to Win by TKO/KO @ 2.10',
  },
  {
    id: 'pred-21',
    matchId: 'match-36',
    homeWinProb: 65,
    drawProb: 0,
    awayWinProb: 35,
    predictedResult: 'home_win',
    confidence: 77,
    overUnder: 'over',
    overUnderLine: 2.5,
    btts: 'yes',
    aiAnalysis: 'Makhachev vs Oliveira is a styles clash for the ages — world-class grappling vs elite submission artistry. Islam has improved his striking dramatically and his wrestling superiority may be too much for Oliveira to withstand.',
    keyFactors: ['Makhachev 94% takedown defence', 'Oliveira 20 submission wins UFC record', 'Islam striking acc 52% last 3 fights', 'Fight likely to go 3+ rounds based on H2H'],
    vipTip: 'Makhachev to Win by Decision @ 2.35',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'mock-user',
    title: 'LIVE: Man City 2-1 Real Madrid',
    body: 'Goal! Haaland scores in the 67th minute. Man City extend their lead!',
    type: 'live',
    read: false,
    createdAt: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'mock-user',
    title: 'New AI Prediction Available',
    body: 'Barcelona vs Atletico Madrid — 88% confidence. Tap to view full analysis.',
    type: 'prediction',
    read: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'mock-user',
    title: 'VIP Tip of the Day',
    body: 'Liverpool Win + BTTS @ 2.40 — Posted by our expert analysts.',
    type: 'vip',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-4',
    userId: 'mock-user',
    title: 'Match Starting Soon',
    body: 'Liverpool vs Chelsea kicks off in 30 minutes. Your prediction is set!',
    type: 'reminder',
    read: true,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'notif-5',
    userId: 'mock-user',
    title: 'Your Prediction Was Correct!',
    body: 'Man United 3-1 Tottenham — You predicted a home win. Nice call!',
    type: 'result',
    read: true,
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    roomId: 'room-1',
    userId: 'user-alpha',
    username: 'SportsMaster',
    content: 'Haaland is absolutely unstoppable right now. City are going all the way this UCL!',
    createdAt: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: 'msg-2',
    roomId: 'room-1',
    userId: 'user-beta',
    username: 'TacticsTalk',
    content: 'Real Madrid always find a way though. Do not write them off yet. Vinicius can change a game in seconds.',
    createdAt: new Date(Date.now() - 90000).toISOString(),
  },
  {
    id: 'msg-3',
    roomId: 'room-1',
    userId: 'user-gamma',
    username: 'xGKing',
    content: 'Per xG model, City have a 52% chance of winning. The stats do not lie.',
    createdAt: new Date(Date.now() - 60000).toISOString(),
  },
  {
    id: 'msg-4',
    roomId: 'room-1',
    userId: 'user-delta',
    username: 'BetPro99',
    content: 'I have City to win and BTTS. Great odds at 1.72 before the match started!',
    createdAt: new Date(Date.now() - 30000).toISOString(),
  },
];

export const VIP_PLANS = [
  {
    id: 'monthly',
    name: 'Monthly VIP',
    price: '$9.99',
    period: '/month',
    features: [
      'Unlimited AI predictions',
      'VIP daily tips from experts',
      'Advanced match analytics',
      'H2H & form statistics',
      'Ad-free experience',
      'Priority chat badge',
    ],
    popular: false,
    color: '#4ECDC4',
  },
  {
    id: 'yearly',
    name: 'Annual VIP',
    price: '$59.99',
    period: '/year',
    badge: 'SAVE 50%',
    features: [
      'Everything in Monthly',
      'AI prediction history',
      'Bankroll management tools',
      'Private VIP chat room',
      'Early access to new features',
      'Personal prediction tracker',
    ],
    popular: true,
    color: '#FFD700',
  },
];
